imranertaza/cCart

app/Config/Routes.php
app/Controllers/Admin/Product_category.php
app/Helpers/Global_helper.php
app/Views/Admin/Order/index.php
app/Views/Admin/Product_category/create.php
app/Views/Admin/Product_category/index.php
app/Views/Admin/Product_category/update.php
app/Views/Admin/Products/create.php
app/Views/Admin/Products/update.php
app/Views/Admin/Settings/index.php
app/Views/Admin/sidebar.php

category improved

---

app/Helpers/Global_helper.php

sort update

---

app/Config/Routes.php
app/Controllers/Admin/Advanced_products.php
app/Controllers/Admin/Products.php
app/Helpers/Global_helper.php
app/Views/Admin/Advanced_products/category.php
app/Views/Admin/Advanced_products/index.php
app/Views/Pagers/custome_link.php
app/Views/Theme/Default/footer.php
app/Views/Theme/Theme_2/footer.php
app/Views/Theme/Theme_3/Home/index.php
app/Views/Theme/Theme_3/footer.php
public_html/admin_assets/dist/js/ajaxScript.php

The following tasks are done in this commits.
1) Add image column before the product name in the admin panel #21 
2) Remove category text from the shop by section at home page of theme 3 #20 
3) Product sorting at the home page. When new products comes, it will show first. #19 
4) Need to fix product description character issue. #10 
5) Zone rate shipping issue > It is not changing the price if we select the shipping method before after setting the address. #11 
6) products feature status is not changing #12 
7) Add "Back" button at the most of the pages for the good user experience. #13
8) Add "search bar" in the bulk edit module. #14
9) Develop item show per page feature so that admin can change it when he needs. #15
10) Change pagination setting so that it can show page number in …

Some module are updated and some are developed and also some issues are fixed.

---

public_html/admin_assets/dist/js/ajaxScript.php

Datatable is not working when updating any fields from bulk edit option.

Datatable is not working when updating any fields from bulk edit option.

---

app/Database/Migrations/2023-11-27-151050_CreatLabelColumInModuleSettings.php

Column migration created for the module settings table #9

Column migration created for the module settings table

---

app/Views/Theme/Theme_3/Checkout/index.php
app/Views/Theme/Theme_3/footer.php

Developed validation on checkout page of theme 3

Developed validation on checkout page of theme 3

---

app/Controllers/Checkout.php
app/Libraries/Flat_shipping.php
app/Libraries/Weight_shipping.php
app/Libraries/Zone_rate_shipping.php
app/Libraries/Zone_shipping.php
app/Views/Theme/Default/Category/index.php
app/Views/Theme/Theme_2/Category/index.php
app/Views/Theme/Theme_3/Category/index.php
public_html/admin_assets/dist/js/ajaxScript.php

Product free shipping is not working along with shipping methods.
#46

Product free shipping is not working along with shipping methods

---

app/Config/Routes.php
app/Controllers/Admin/Dashboard.php
app/Controllers/Admin/Order.php
app/Controllers/Admin/Theme_settings.php
app/Controllers/Checkout.php
app/Views/Admin/Dashboard/index.php
app/Views/Admin/Theme_settings/index.php
app/Views/Admin/header.php
app/Views/Theme/Default/header.php
app/Views/Theme/Theme_2/header.php
app/Views/Theme/Theme_3/header.php

Improved Dashboard and made febicon dynamic.
#51 
#50

Improve Dashboard 

---

app/Views/Theme/Default/Checkout/index.php
app/Views/Theme/Default/Customer/dashboard.php
app/Views/Theme/Default/Customer/profile.php
app/Views/Theme/Default/Login/forgotPassword.php
app/Views/Theme/Default/Login/login.php
app/Views/Theme/Default/Login/otp_submit.php
app/Views/Theme/Default/Login/register.php
app/Views/Theme/Default/Login/reset_password.php
app/Views/Theme/Default/Page/contact.php
app/Views/Theme/Default/footer.php
app/Views/Theme/Theme_2/Checkout/index.php
app/Views/Theme/Theme_2/Customer/dashboard.php
app/Views/Theme/Theme_2/Customer/profile.php
app/Views/Theme/Theme_2/Login/forgotPassword.php
app/Views/Theme/Theme_2/Login/login.php
app/Views/Theme/Theme_2/Login/otp_submit.php
app/Views/Theme/Theme_2/Login/register.php
app/Views/Theme/Theme_2/Login/reset_password.php
app/Views/Theme/Theme_2/Page/contact.php
app/Views/Theme/Theme_2/footer.php
app/Views/Theme/Theme_3/Login/reset_password.php
public_html/assets/assets_fl/validation.js

customer panel in default theme and contact page theme 2 and default theme validation is done.
#75 
#74 
#73 
#72 
#71 
#70 
#69 
#68 
#67 
#66 
#65 
#64 
#63 
#62 
#61

 customer panel in default theme and contact page theme 2 and default theme validation is done.

---

app/Views/Theme/Theme_3/Home/index.php
public_html/assets/assets_fl/style.css
public_html/assets/assets_fl/validation.js

Responsive issue is fixed for the theme 3
#8

Index page responsive issu fixd

---

app/Controllers/Admin/Theme_settings.php

Duplicated function removed named "favicon_update"

Duplicated function removed named "favicon_update"

---

app/Config/Routes.php
app/Controllers/Admin/Payment/Bank_transfer.php
app/Controllers/Admin/Payment/Bitcoin.php
app/Controllers/Admin/Payment/Cash_on_delivery.php
app/Controllers/Admin/Payment/Credit_card.php
app/Controllers/Admin/Payment/MoneyGram.php
app/Controllers/Admin/Payment/Paypal.php
app/Controllers/Admin/Payment/U_wallet.php
app/Controllers/Admin/Payment/Western_union.php
app/Controllers/Admin/Theme_settings.php
app/Controllers/Checkout.php
app/Controllers/Pages/Pages.php
app/Helpers/Global_helper.php
app/Views/Admin/Advanced_products/index.php
app/Views/Admin/Payment/index.php
app/Views/Admin/Payment/u_wallet.php
app/Views/Theme/Theme_3/Checkout/index.php
app/Views/Theme/Theme_3/Page/contact.php
app/Views/Theme/Theme_3/footer.php
public_html/admin_assets/dist/js/ajaxScript.php
public_html/assets/assets_fl/style.css

Fixed some issues and made some improvements.
#82 
#83 
#84 
#85 
#86 
#87 
#88 
#89 
#90 
#91 
#92

Fixed some issues and made some improvements.

---

app/Config/Routes.php
app/Controllers/Admin/Payment/Bank_transfer.php
app/Controllers/Admin/Payment/Bitcoin.php
app/Controllers/Admin/Payment/Cash_on_delivery.php
app/Controllers/Admin/Payment/Credit_card.php
app/Controllers/Admin/Payment/MoneyGram.php
app/Controllers/Admin/Payment/Paypal.php
app/Controllers/Admin/Payment/U_wallet.php
app/Controllers/Admin/Payment/Western_union.php
app/Controllers/Admin/Theme_settings.php
app/Controllers/Checkout.php
app/Controllers/Pages/Pages.php
app/Helpers/Global_helper.php
app/Views/Admin/Advanced_products/index.php
app/Views/Admin/Payment/index.php
app/Views/Admin/Payment/u_wallet.php
app/Views/Theme/Theme_3/Checkout/index.php
app/Views/Theme/Theme_3/Page/contact.php
app/Views/Theme/Theme_3/footer.php
public_html/admin_assets/dist/js/ajaxScript.php
public_html/assets/assets_fl/style.css

Fixed some issues in the commit.

---

app/Config/Routes.php
app/Controllers/Admin/Advanced_products.php
app/Controllers/Admin/Products.php
app/Controllers/Admin/Theme_settings_3.php
app/Controllers/Cart/Cart.php
app/Controllers/Checkout.php
app/Controllers/Login.php
app/Controllers/Products/Products.php
app/Views/Admin/Advanced_products/category.php
app/Views/Admin/Advanced_products/category_view.php
app/Views/Admin/Advanced_products/index.php
app/Views/Admin/Advanced_products/row.php
app/Views/Admin/Products/update.php
app/Views/Admin/Theme_settings/theme_3.php
app/Views/Theme/Theme_3/Checkout/index.php
app/Views/Theme/Theme_3/Home/index.php
app/Views/Theme/Theme_3/Page/contact.php
app/Views/Theme/Theme_3/footer.php
public_html/admin_assets/dist/js/ajaxScript.php
public_html/assets/assets_fl/style.css

new correction is done. Some issues are fixed.
#117 
#118 
#119 
#120 
#121 
#122 
#123 
#124 
#125

 new correction is done. Some issues are fixed.

---

app/Config/Routes.php
app/Controllers/Admin/Advanced_products.php
app/Controllers/Admin/Products.php
app/Views/Admin/Advanced_products/index.php
app/Views/Admin/Advanced_products/option.php
app/Views/Admin/Advanced_products/row.php
public_html/admin_assets/dist/js/ajaxScript.php

bulkedit need new add option system
#128

 bulkedit need new add option system

---

app/Controllers/Products.php

 option search improved

---

app/Controllers/Admin/Products.php

 some bug fixed

---

.github/.workflows/phpunit.yml
.gitignore
phpunit.xml.dist
tests/app/Libraries/FilterTest.php

Added php unit test with it.

---

.github/workflows/phpunit.yml

Added php unit test with it. 

---

tests/app/Libraries/FilterTest.php

Added Mysql to yml so that it install mysql and connect our application with it.

Added Mysql to yml so that it install mysql and connect our application with it.

---

.github/workflows/phpunit.yml

Added Migration and Seeder command with it.

Added Migration and Seeder command with it.

---

.env.sample
.github/workflows/phpunit.yml
tests/app/Libraries/DatabaseTest.php

Added a testing for that checks if functions that are connected with database tests well.

Added a testing for that checks if functions that are connected with database tests well.

---

app/Config/Routes.php
app/Controllers/Home.php
app/Controllers/Products.php
app/Helpers/Global_helper.php
app/Libraries/Filter.php
app/Views/Theme/Theme_3/Category/index.php
app/Views/Theme/Theme_3/Checkout/index.php
app/Views/Theme/Theme_3/Page/contact.php
app/Views/Theme/Theme_3/Page/site_map.php
app/Views/Theme/Theme_3/Product/detail.php
app/Views/Theme/Theme_3/footer.php
app/Views/Theme/Theme_3/header.php
public_html/assets/assets_fl/details.js
public_html/assets/assets_fl/style.css
public_html/sitemap.xml

developed so many things in this commit

developed so many things in this commit

---

app/Config/Encryption.php
app/Controllers/Home.php
app/Views/Theme/Theme_3/header.php
public_html/assets/assets_fl/style.css

some changes is made for the correction.

some changes is made for the correction

---

app/Views/Theme/Theme_3/header.php

header link change

---

app/Libraries/Image_processing.php

Update filter library to fix the image array size issue

Update filter library to fix the image array size issue

---

README.md
app/Views/Admin/Products/create.php
app/Views/Admin/Products/list.php
app/Views/Theme/Default/Album/index.php
app/Views/Theme/Default/Album/view.php
app/Views/Theme/Default/header.php
app/Views/Theme/Theme_2/Album/index.php
app/Views/Theme/Theme_2/Album/view.php
app/Views/Theme/Theme_2/footer.php
app/Views/Theme/Theme_2/header.php

 payment or modeul name listed

---

app/Config/Routes.php
app/Controllers/OisbizcraftController.php

OISBizcraft payment gateway is being developed. And the problem of showing login page instead of payment page is solved.

OISBizcraft payment gateway is being developed. And the problem of showing login page instead of payment page is solved.

---

app/Config/Routes.php
app/Controllers/Admin/Order.php
app/Controllers/OisbizcraftController.php
app/Controllers/Paypal.php
app/Controllers/StripeController.php
app/Views/Admin/Order/order_view.php
app/Views/Theme/Theme_3/Customer/invoice.php

developed the osi bizcraft payment gateway.

developed the osi bizcraft payment gateway.

---

app/Config/Routes.php
app/Controllers/OisbizcraftController.php

OISBizcraft payment gateway is done successfully.

OISBizcraft payment gateway is done successfully.

---

app/Config/Routes.php
app/Controllers/OisbizcraftController.php
app/Database/Migrations/2023-05-25-135327_Order.php
app/Views/Admin/Payment/oisbizcraft.php
app/Views/Theme/Default/Album/index.php
app/Views/Theme/Default/Customer/menu.php
app/Views/Theme/Default/header.php
app/Views/Theme/Theme_2/Album/index.php
app/Views/Theme/Theme_2/Customer/menu.php
app/Views/Theme/Theme_2/Customer/walllet.php
app/Views/Theme/Theme_2/header.php
app/Views/Theme/Theme_3/Album/index.php
app/Views/Theme/Theme_3/Customer/menu.php
app/Views/Theme/Theme_3/Customer/walllet.php
app/Views/Theme/Theme_3/header.php

Developed so many things

---

app/Controllers/Admin/Album.php
app/Controllers/Admin/Products.php

php ini set remove

---

app/Controllers/Admin/Blog.php
app/Controllers/Category.php
app/Controllers/Products.php
app/Views/Admin/Advanced_products/category_edit.php
app/Views/Admin/Advanced_products/multi_attribute.php
app/Views/Admin/Advanced_products/multi_option.php
app/Views/Admin/Products/status_update.php
app/Views/Admin/layout.php
app/Views/Theme/Theme_3/Category/index.php

Add a "back" button to everywhere needed.

Add a "back" button to everywhere needed.

---

app/Config/Routes.php
app/Controllers/Admin/Products.php
app/Controllers/Admin/Settings.php
app/Helpers/Global_helper.php
app/Views/Admin/Settings/index.php
app/Views/Theme/Default/Customer/customer_ledger.php
app/Views/Theme/Default/Customer/customer_point_history.php
app/Views/Theme/Default/Customer/order.php
app/Views/Theme/Default/Customer/walllet.php
app/Views/Theme/Default/footer.php
app/Views/Theme/Default/header.php
app/Views/Theme/Theme_2/Category/index.php
app/Views/Theme/Theme_2/Customer/customer_ledger.php
app/Views/Theme/Theme_2/Customer/customer_point_history.php
app/Views/Theme/Theme_2/Customer/order.php
app/Views/Theme/Theme_2/Customer/walllet.php
app/Views/Theme/Theme_2/footer.php
app/Views/Theme/Theme_2/header.php
app/Views/Theme/Theme_3/Product/detail.php
app/Views/Theme/Theme_3/footer.php
public_html/assets/theme_3/details.css

Developed cache file delete section.

Developed cache file delete section.

---

.github/workflows/deploy_to_theme1_server.yml

Update and rename deploy.yml to deploy_to_theme1_server.yml

Update and rename deploy.yml to deploy_to_theme1_server.yml

---

app/Views/Theme/Theme_3/header.php

compare error

---

app/Config/Filters.php
app/Filters/MinifyHtml.php

Added filter to minify html, inline css and inline js.

Added filter to minify html, inline css and inline js.
